language: node_js
node_js:
  - "lts/*"
cache:
  directories:
  - node_modules
bundler_args: --retry 5
script:
  - travis_wait 30 sleep 1800 &
  - npm test
  - npm run build
after_success:
  - npm run coveralls
